# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Final Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final Project
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Auth'
  pod 'SDWebImage', '~> 5.0'

  target 'Final ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Final ProjectUITests' do
    # Pods for testing
  end

end
